# Generated by Django 4.2.7 on 2025-08-03 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='稳定ID')),
                ('name', models.CharField(default='未命名客户端', max_length=100, verbose_name='连接名称')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.PositiveIntegerField(default=8765, verbose_name='端口')),
                ('connection_key', models.CharField(max_length=255, verbose_name='连接密钥')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
                ('is_connected', models.BooleanField(default=False, verbose_name='是否已连接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_connected_at', models.DateTimeField(blank=True, null=True, verbose_name='最后连接时间')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('reconnect_count', models.PositiveIntegerField(default=0, verbose_name='重连次数')),
                ('total_connect_time', models.DurationField(blank=True, null=True, verbose_name='总连接时长')),
                ('client_version', models.CharField(blank=True, max_length=50, verbose_name='客户端版本')),
                ('client_features', models.JSONField(blank=True, default=list, verbose_name='客户端功能列表')),
            ],
            options={
                'verbose_name': '客户端连接',
                'verbose_name_plural': '客户端连接',
                'ordering': ['-last_connected_at', '-created_at'],
            },
        ),
    ]
